In [18]:
## bagging 回归
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
df = pd.DataFrame([[1,5.56],[2,5.7],[3,5.91],[4,6.4],[5,6.8],[6,7.05],[7,8.9],[8,8.7],[9,9],[10,9.05]])
M = [] #存储决策树模型的数组
n_trees = 1000  #设置树的颗数
for i in range(n_trees):  #训练多棵树
    tmp = df.sample(frac=0.9,replace=True)#对样本进行采样，目的是建造不同的树
    X = tmp.iloc[:,[0]] #构造X
    Y = tmp.iloc[:,[-1]]  #构造Y
    model = DecisionTreeRegressor(max_depth=1).fit(X,Y)  #新建决策树模型
    #将决策树模型加入数组
    M.append(model)
    #打印每个基础模型的效果

X = df.iloc[:,[0]]#获取全部数据的X
Y = df.iloc[:,[-1]]#获取全部数据的Y
res = np.zeros(df.shape[0])#初始化全零向量
for i in M: #遍历模型数组
    res += i.predict(X) #将每个模型预测值叠加到res变量
#取平均输出最终对每个样本标签的预测值
res/n_trees


array([6.23361396, 6.23361396, 6.23361396, 6.2393248 , 6.27482499,
       6.57431752, 8.15573042, 8.83172935, 8.8956078 , 8.8956078 ])

In [29]:
##boosting 回归
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
df = pd.DataFrame([[1,5.56],[2,5.7],[3,5.91],[4,6.4],[5,6.8]
                   ,[6,7.05],[7,8.9],[8,8.7],[9,9],[10,9.05]],columns=["x","y"])

M = [] #存储决策树模型的数组
n_trees = 76  #设置树的颗数
X = df.iloc[:,[0]] #构造X
Y = df.iloc[:,[-1]]#构造Y
for i in range(n_trees):  
    model = DecisionTreeRegressor(max_depth=1).fit(X,Y)  #新建决策树模型
    #将决策树模型加入数组
    M.append(model)
    Y_het = model.predict(X)#输出模型预测值
    Y_het = pd.DataFrame(Y_het,columns=["y"])#将模型预测值转为DataFrame
    Y = Y -Y_het#改变原始的Y，让下一个学习器继续学习
res =  np.zeros(df.shape[0])#初始化全零向量
for i in M: #遍历模型数组
    res += i.predict(X) #将每个模型预测值叠加到res变量
#输出最终对每个样本标签的预测值
res

array([5.56115025, 5.70252961, 5.90632014, 6.40342107, 6.79910519,
       7.04628398, 8.90037085, 8.70299739, 8.99769121, 9.05013031])

In [39]:
##bagging 分类
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
df = pd.DataFrame([[0,1],[1,1],[2,1],[3,-1],[4,-1],
                   [5,-1],[6,1],[7,1],[8,1],[9,-1]])
M = []#存储决策树模型的数组
n_trees = 101  #设置树的颗数
for i in range(n_trees):  
    tmp = df.sample(frac=0.9,replace=True)#对样本进行采样，目的是建造不同的树
    X = tmp.iloc[:,[0]]#构造X
    Y = tmp.iloc[:,[-1]]#构造Y
    model = DecisionTreeClassifier(max_depth=3).fit(X,Y)#新建决策树模型

    #将决策树模型加入数组
    M.append(model)
    #打印每个基础模型的效果
    #     print(model.score(X,Y))

X = df.iloc[:,[0]]#获取全部数据的X
Y = df.iloc[:,[-1]]#获取全部数据的Y
res =  np.zeros(df.shape[0])#初始化全零向量
for model in M: #遍历模型数组
    res += model.predict(X) #将每个模型预测值叠加到res变量
#取平均输出最终对每个样本标签的预测值
np.sign(res)
res

array([ 95.,  95.,  87., -47., -95., -83.,  41.,  91.,  73., -27.])