In [1]:
import pandas as pd 
from sklearn.feature_extraction.text import CountVectorizer #计算词频的包
path = 'datas/bayes_xinxi.txt'
df = pd.read_csv(path)
df
tfCoder = CountVectorizer(token_pattern='[a-zA-Z|\u4e00-\u9fa5]+')
tfCoder.fit(df['words'])

Y                     words
0  1   Chinese Beijing Chinese
1  1  Chinese Chinese Shanghai
2  1             Chinese Macao
3  0       Tokyo Japan Chinese

In [7]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
df = pd.read_csv("datas/bayes_xinxi.txt")
tfCoder = CountVectorizer(token_pattern="[a-zA-Z|\u4e00-\u9fa5]+")
X = df["words"]
Y = df["Y"]
X

0     Chinese Beijing Chinese
1    Chinese Chinese Shanghai
2               Chinese Macao
3         Tokyo Japan Chinese
Name: words, dtype: object

In [124]:
X = tfCoder.fit_transform(X)
print(tfCoder.get_feature_names())
print(X.toarray())
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X,Y)
T = ['Chinese Chinese Chinese Tokyo Japan']
print(model.predict(tfCoder.transform(T).toarray()))

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 2 0 0 0 0]
 [0 2 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]
[1]


In [5]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
df = pd.read_csv("datas/bayes_xinxi.txt")  #读取数据
tfCoder = CountVectorizer(token_pattern="[a-zA-Z|\u4e00-\u9fa5]+")#TF模型
lam = 1
tfCoder.fit(df["words"])#训练TF模型，只需要fit一次，确定词表
names_feature = tfCoder.get_feature_names()  #获取词语名  

print(names_feature)
Y =  list(set(df["Y"]))#获取类别种类的list
class_prior = [] #用于存储先验概率
feature_prob = [] #用于存储条件概率
for y in Y: #遍历每个类别
    df2 = df[df["Y"]==y]#获取每个类别下的DF

    prior = df2.shape[0]/df.shape[0] #计算先验概率
    class_prior.append(prior)#将先验概率加入集合
    
    a = tfCoder.transform(df2["words"]).toarray()
    prob = (a.sum(axis=0) + lam)/(a.sum()+len(names_feature))#计算条件概率
    feature_prob.append(prob)#将条件概率加入集合
    
feature_prob = np.array(feature_prob)
print("feature_prob",feature_prob)
print("-----------进行测试-----------")
X = ['Chinese Chinese Chinese Tokyo Japan'] #训练数据
X = tfCoder.transform(X).toarray()  #将训练数据转为array类型
print("X",X)
past = feature_prob**X #求后验概率
print("past",past)
#输出概率最大的类别
Y[np.argmax(np.exp(np.sum(np.log(past),axis=1))*class_prior)]

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
feature_prob [[0.11111111 0.22222222 0.22222222 0.11111111 0.11111111 0.22222222]
 [0.14285714 0.42857143 0.07142857 0.14285714 0.14285714 0.07142857]]
-----------进行测试-----------
X [[0 3 1 0 0 1]]
past [[1.         0.01097394 0.22222222 1.         1.         0.22222222]
 [1.         0.0787172  0.07142857 1.         1.         0.07142857]]


1

In [155]:
from sklearn.feature_extraction.text import CountVectorizer
X = ['我 爱 你','我 恨 你 恨 你']
y = [0,1]
countCoder = CountVectorizer(token_pattern="[a-zA-Z|\u4e00-\u9fa5]+")
X = countCoder.fit_transform(X)
print(countCoder.get_feature_names())  
print(X.toarray())
# ['你', '恨', '我', '爱']
# [[1 0 1 1]
#  [2 2 1 0]]


['你', '恨', '我', '爱']
[[1 0 1 1]
 [2 2 1 0]]


[0 0 1 0 1 1]
[0 0 1 0 1 1]
[1 1 0]


In [4]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer
from sklearn.model_selection import train_test_split
df = pd.read_csv("datas/bayes_wenben.txt",header=None)


X = df[1]
Y = df[0]
tfCoder = CountVectorizer(token_pattern="[a-zA-Z|\u4e00-\u9fa5]+")
X = tfCoder.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.5)
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train,y_train)
print(y_test.shape[0])
print(sum(model.predict(X_test)==y_test.values)/y_test.shape[0])

4886
0.8528448628735161
