In [1]:
import numpy as np
X = np.array([[1, 2], [2, 2], [6, 8],[7 ,8]])
C = np.array([[1.0, 2.0], [2.0, 2.0]]) #聚类中心
iters = 3 #迭代次数
while iters>0 :
    iters -= 1
    B = []
    for c in C:#遍历每一个聚类中心，计算样本到每个聚类中心的距离
        a = ((X - c)**2).sum(axis=1)
#         print(a)
        B.append(a)
    #将样本分配到所属的聚类中心
    min_index = np.argmin(np.array(B),axis=0)
    print(min_index)
    for i in range(len(C)):#获取每个簇的样本，求质心更新C
        a = np.mean(X[min_index == i],axis=0)
        C[i] = a
#         print(a)
#打印聚类中心
print(C)
#打印所有样本的所属的簇
min_index

[0 1 1 1]
[0 0 1 1]
[0 0 1 1]
[[1.5 2. ]
 [6.5 8. ]]


array([0, 0, 1, 1], dtype=int64)