In [17]:
import numpy as np
A = np.array([
    [0.5,0.2,0.3],
    [0.3,0.5,0.2],
    [0.2,0.3,0.5]
])
B = np.array([[0.5,0.5],[0.4,0.6],[0.7,0.3]])
pi = np.array([0.2,0.4,0.4])
observ = [0,1,0]

alpha = pi * B[:,0]
print(alpha)

for i in observ[1:]:
    res = []
    for j in range(len(pi)):
        a = sum(alpha * A[:,j])* B[j][i]
        res.append(a)
    alpha = np.array(res)

sum(alpha)

[0.1  0.16 0.28]


0.130218

In [29]:
# a = open("test.txt",encoding="utf-8",mode='a')
# a.write("hello world3\n")
# a.close()

for i in open("test.txt",encoding="utf-8"):
    print(i,end="")

hello world2hello world2hello world3hello world3
hello world3
hello world3
hello world3


In [ ]:
A_name = ["晴天","阴天","雨天"]
A = np.array([[0.6, 0.3, 0.1],
              [0.4, 0.3, 0.3],
              [0.1, 0.2, 0.7]])
B_name = ["郊游","购物","看书","睡觉"]
B = np.array([[0.7, 0.2, 0.1, 0.0],
              [0.2, 0.5, 0.2, 0.1],
              [0.0, 0.0, 0.6, 0.4]])
pi = np.array([0.4, 0.4, 0.2])

In [30]:
import numpy as np
import random
file = open('generate.txt', encoding='utf-8', mode='w')

A_name = ["晴天","阴天","雨天"]
A = np.array([[0.6, 0.3, 0.1],
              [0.4, 0.3, 0.3],
              [0.1, 0.2, 0.7]])
B_name = ["郊游","购物","看书","睡觉"]
B = np.array([[0.7, 0.2, 0.1, 0.0],
              [0.2, 0.5, 0.2, 0.1],
              [0.0, 0.0, 0.6, 0.4]])
pi = np.array([0.4, 0.4, 0.2])

for months in range(500):
    
    a = random.choices(A_name, weights=pi)[0]
    b = random.choices(B_name, weights=B[A_name.index(a), :])[0]
    d = a+'|'+b+' '*4
    file.write(d)
    for days in range(29):
        a = random.choices(A_name, weights=A[A_name.index(a),:])[0]
        b = random.choices(B_name, weights=B[A_name.index(a), :])[0]
        d = a+'|'+b+' '*4
        file.write(d)
    file.write('\n')
#     break
file.close()

In [81]:
a = [0.8,0.2]
b = ["a","b"]
random.choices(b,weights=a)


['a']

In [180]:
import numpy as np
import random
import time
start = time.time()
random.seed(666)
A_name = ["晴天","阴天","雨天"]
A = np.array([[0.6, 0.3, 0.1],
              [0.4, 0.3, 0.3],
              [0.1, 0.2, 0.7]])
B_name = ["郊游","购物","看书","睡觉"]
B = np.array([[0.7, 0.2, 0.1, 0.0],
              [0.2, 0.5, 0.2, 0.1],
              [0.0, 0.0, 0.6, 0.4]])
pi = np.array([0.4, 0.4, 0.2])

writer = open("zyc_daily.txt",encoding="utf-8",mode='w')
# (1)按照初始状态分布π产生状态 i1
state = random.choices(A_name,weights=pi)[0] #第一个状态
tmp = ""
# (2)令 t=1
for line in range(500):
    for i in range(30):
        # (3)按照状态 it 的观测概率分布生成ot
        ob = random.choices(B_name,weights=B[A_name.index(state),:])[0]  #第一个观测
        tmp += ob +"/"+state+"\t"
        # (4)按照状态 it 的状态转移概率分布产生状态it+1 
        state = random.choices(A_name,weights=A[A_name.index(state),:])[0]
        # (5)令 t=t+1；如果t<T，转步(3)；否则终止
    tmp += "\n"
    writer.write(tmp)
    tmp = ""
    state = random.choices(A_name,weights=pi)[0] #第一个状态
# writer.write(tmp)
writer.close()
end = time.time()
end  - start

0.15858030319213867

In [1]:
import numpy as np
import random
import time
start = time.time()
random.seed(666)
A_name = ["晴天","阴天","雨天"]
A = np.array([[0.6, 0.3, 0.1],
              [0.4, 0.3, 0.3],
              [0.1, 0.2, 0.7]])
B_name = ["郊游","购物","看书","睡觉"]
B = np.array([[0.7, 0.2, 0.1, 0.0],
              [0.2, 0.5, 0.2, 0.1],
              [0.0, 0.0, 0.6, 0.4]])
pi = np.array([0.4, 0.4, 0.2])

states = []
observes = []
writer = open("zyc_daily.txt",encoding="utf-8",mode='w')
# (1)按照初始状态分布π产生状态 i1
state = random.choices(A_name,weights=pi)[0] #第一个状态
# (2)令 t=1
for line in range(1000):
    for i in range(30):
        # (3)按照状态 it 的观测概率分布生成ot
        ob = random.choices(B_name,weights=B[A_name.index(state),:])[0]  #第一个观测
        writer.write(ob +"/"+state+"\t")
        # (4)按照状态 it 的状态转移概率分布产生状态it+1 
        state = random.choices(A_name,weights=A[A_name.index(state),:])[0]
        # (5)令 t=t+1；如果t<T，转步(3)；否则终止
    writer.write("\n")
    state = random.choices(A_name,weights=pi)[0] #第一个状态
writer.close()
end = time.time()
end  - start

0.34308338165283203

In [189]:
dic = {"小米":3599,"华为":5000}
a = "小米"
if a in dic:
    print(111)

111


In [13]:
import numpy as np
A_name = ["晴天","阴天","雨天"]
# A = np.array([[0.6, 0.3, 0.1],
#               [0.4, 0.3, 0.3],
#               [0.1, 0.2, 0.7]])
B_name = ["郊游","购物","看书","睡觉"]
# B = np.array([[0.7, 0.2, 0.1, 0.0],
#               [0.2, 0.5, 0.2, 0.1],
#               [0.0, 0.0, 0.6, 0.4]])
# pi = np.array([0.4, 0.4, 0.2])
pi = {}
A = {}
B = {}
for line in open("zyc_daily.txt",encoding="utf-8"):
    lst2D = [i.split("/") for i in line[:-2].split("\t")] #[['睡觉', '阴天'], ['购物', '阴天'], 
    key = lst2D[0][1]
    if key not in pi:
        pi[key] = 1
    else:
        pi[key] += 1
        
    for i in range(len(lst2D)-1):
        key = lst2D[i][1] + lst2D[i+1][1]
        if key not in A:
            A[key] = 1
        else:
            A[key] += 1
            
    for lst in lst2D:  #[['睡觉', '阴天'], ['
        key = lst[1] + lst[0]
        if key not in B:
            B[key] = 1
        else:
            B[key] += 1
B

{'阴天睡觉': 809,
 '阴天购物': 3929,
 '雨天看书': 6733,
 '雨天睡觉': 4413,
 '晴天购物': 2196,
 '阴天郊游': 1515,
 '晴天郊游': 7717,
 '阴天看书': 1612,
 '晴天看书': 1076}

In [5]:
dic = {'阴天睡觉': 809,
 '阴天购物': 3929,
 '雨天看书': 6733,
 '雨天睡觉': 4413,
 '晴天购物': 2196,
 '阴天郊游': 1515,
 '晴天郊游': 7717,
 '阴天看书': 1612,
 '晴天看书': 1076}
print(dic)
A_name = ["晴天","阴天","雨天"]
for key,value in dic.items():
    

{'阴天睡觉': 809, '阴天购物': 3929, '雨天看书': 6733, '雨天睡觉': 4413, '晴天购物': 2196, '阴天郊游': 1515, '晴天郊游': 7717, '阴天看书': 1612, '晴天看书': 1076}
809
3929
6733
4413
2196
1515
7717
1612
1076


In [1]:
#无监督学习 隐马尔科夫模型的学习问题：给观测序列 推算 模型参数
import numpy as np
from hmmlearn import hmm
states = ["box 1", "box 2", "box 3"]
observations = ["red", "white"]
model = hmm.MultinomialHMM(n_components=len(states), n_iter=20, tol=0.01)
seen = np.array([[0,1,0,1],[0,0,0,1],[1,0,1,1]])
model.fit(seen)
print(model.startprob_)
print()
print(model.transmat_)
print()
print(model.emissionprob_) 

# [  8.67510767e-11   1.00000000e+00   4.41182118e-12] #初始概率分布
# [[  1.75337963e-01   6.41371396e-01   1.83290641e-01]  #状态转移概率分布
#  [  4.49292494e-01   3.28996871e-05   5.50674606e-01]
#  [  1.96457695e-01   5.94861793e-01   2.08680511e-01]]
# [[ 0.18339428  0.81660572] #观测概率分布
#  [ 0.99896576  0.00103424]
#  [ 0.1505637   0.8494363 ]]


[2.21164204e-53 1.00000000e+00 9.50861895e-16]

[[3.74962315e-01 4.70502125e-01 1.54535560e-01]
 [5.99866988e-01 1.47154549e-08 4.00132997e-01]
 [2.33758102e-02 9.48677245e-01 2.79469444e-02]]

[[4.29109220e-04 9.99570891e-01]
 [9.99954032e-01 4.59682907e-05]
 [3.89668151e-01 6.10331849e-01]]


In [7]:
import numpy as np
from hmmlearn import hmm
states = ["box 1", "box 2", "box 3"]
observations = ["red", "white"]
model = hmm.MultinomialHMM(n_components=len(states), n_iter=20, tol=0.01)
B_name = ["郊游","购物","看书","睡觉"]
B=[]
for line in open("zyc_daily.txt",encoding="utf-8"):
    a = [i.split("/") for i in line[:-2].split("\t")] #[['睡觉', '阴天'], ['购物', '阴天'], 
    b=[]
    for j in range(len(a)):        
        b.append(B_name.index(a[j][0]))
    B.append(b)

seen = np.array(B)
model.fit(seen)
print(model.startprob_)
print()
print(model.transmat_)
print()
print(model.emissionprob_) 

[6.63658678e-15 3.14497113e-09 9.99999997e-01]

[[0.42254127 0.28586968 0.29158905]
 [0.30700558 0.52086236 0.17213206]
 [0.44936857 0.23792007 0.31271136]]

[[0.31136335 0.04348903 0.5672438  0.07790382]
 [0.47942077 0.26158291 0.17076673 0.08822959]
 [0.06063206 0.36859673 0.1291769  0.44159431]]


In [16]:
dp = [[2,2,2],[1,1,2]]
start = 0
states = [start]

for i in dp[::-1]:
    states.append(i[start])
    start = i[start]
states.reverse()
states

[2, 1, 0]

In [20]:
import numpy as np
A = np.array([
    [0.5,0.2,0.3],
    [0.3,0.5,0.2],
    [0.2,0.3,0.5]
])
B = np.array([[0.5,0.5],[0.4,0.6],[0.7,0.3]])
pi = np.array([0.2,0.4,0.4])
observ = [0,1,0]
alpha = pi * B[:,0]

result = []
for i in observ[1:]: #遍历观测
    res = [];index = []
    for j in range(len(pi)): #遍历状态
        a = alpha * A[:,j] * B[j][i]
        res.append(a)
        index.append(np.argmax(a))
    alpha = np.max(res,axis=1)
    result.append(index)
    
start = np.argmax(alpha)
states = [start]
for i in result[::-1]:
    states.append(i[start])
    start = i[start]
states.reverse()
states

array([0.1 , 0.16, 0.28])