In [2]:
#给定模型 和 观测序列，计算在模型 下观测序列出现的概率
import numpy as np
from hmmlearn import hmm
import math
states = ["box 1", "box 2", "box 3"]
observations = ["red", "white"]
start_probability = np.array([0.2, 0.4, 0.4])
transition_probability = np.array([
  [0.5, 0.2, 0.3],
  [0.3, 0.5, 0.2],
  [0.2, 0.3, 0.5]
])
emission_probability = np.array([
  [0.5, 0.5],
  [0.4, 0.6],
  [0.7, 0.3]
])

model = hmm.MultinomialHMM(n_components=len(states))
model.startprob_=start_probability
model.transmat_=transition_probability
model.emissionprob_=emission_probability

ball_picked = [0,1,0]
seen = np.array([ball_picked]).T

a = model.score(seen) #score函数返回的是以自然对数为底的对数概率值ֵ
print(math.exp(a))



# result:
# 0.130218
# 给定模型 和 观测序列，计算在模型 下观测序列出现的概率:0.130218




0.13021800000000003


In [ ]:
#无监督学习 隐马尔科夫模型的学习问题：给观测序列 推算 模型参数
import numpy as np
from hmmlearn import hmm
states = ["box 1", "box 2", "box 3"]
observations = ["red", "white"]
model = hmm.MultinomialHMM(n_components=len(states), n_iter=20, tol=0.01)
seen = np.array([[0,1,0,1],[0,0,0,1],[1,0,1,1]])
model.fit(seen)
print(model.startprob_)
print()
print(model.transmat_)
print()
print(model.emissionprob_) 

# [  8.67510767e-11   1.00000000e+00   4.41182118e-12] #初始概率分布
# [[  1.75337963e-01   6.41371396e-01   1.83290641e-01]  #状态转移概率分布
#  [  4.49292494e-01   3.28996871e-05   5.50674606e-01]
#  [  1.96457695e-01   5.94861793e-01   2.08680511e-01]]
# [[ 0.18339428  0.81660572] #观测概率分布
#  [ 0.99896576  0.00103424]
#  [ 0.1505637   0.8494363 ]]



In [3]:
#coding=utf-8
#解码问题：给定模型和观测序列，求最有可能的对应的状态序列
import numpy as np
from hmmlearn import hmm
states = ["box 1", "box 2", "box3"]
observations = ["red", "white"]
start_probability = np.array([0.2, 0.4, 0.4])
transition_probability = np.array([
  [0.5, 0.2, 0.3],
  [0.3, 0.5, 0.2],
  [0.2, 0.3, 0.5]
])
emission_probability = np.array([
  [0.5, 0.5],
  [0.4, 0.6],
  [0.7, 0.3]
])
model = hmm.MultinomialHMM(n_components=len(states))
model.startprob_=start_probability
model.transmat_=transition_probability
model.emissionprob_=emission_probability
ball_picked = [0,1,0]
seen = np.array([ball_picked]).T
states_predict = model.predict(seen)
print("The ball picked:", ", ".join([observations[i] for i in ball_picked]) )
print( "The ball picked:", ", ".join([states[i] for i in states_predict])) 
# result:
# The ball picked: red, white, red
# The ball picked: box3, box3, box3
# 给定模型和观测序列，求最有可能的对应的状态序列: box3, box3, box3


The ball picked: red, white, red
The ball picked: box3, box3, box3
