In [3]:
import numpy as np
import pandas as pd
path='datas/household_power_consumption_1000.txt'
df = pd.read_csv(filepath_or_buffer=path,sep=";")#使用pandas加载csv

## 对数据集增加偏置，并去除掉不需要的列
b = pd.DataFrame([1.0]*df.shape[0],columns=["b"]) #建立一列为1的dataframe，起名为b作为偏置项
df = pd.concat(objs=[df,b],axis=1)#将偏置项合并到原始dataframe

#获取Global_active_power、Global_reactive_power、Global_intensity和偏置列b的dataframe
df = df[["Global_active_power","Global_reactive_power","Global_intensity","b"]]
df = df.replace(to_replace="?",value=np.nan)
from sklearn.preprocessing import Imputer
immodel = Imputer()
df = immodel.fit_transform(df)
# df["Global_active_power"] = df["Global_active_power"].astype(np.float64)
# df.describe()
pd.DataFrame(df)


0      1     2    3
0    2.416973  0.418  18.4  1.0
1    5.360000  0.436  23.0  1.0
2    5.374000  0.498  23.0  1.0
3    5.388000  0.502  23.0  1.0
4    3.666000  0.528  15.8  1.0
5    3.520000  0.522  15.0  1.0
6    3.702000  0.520  15.8  1.0
7    3.700000  0.520  15.8  1.0
8    3.668000  0.510  15.8  1.0
9    3.662000  0.510  15.8  1.0
10   4.448000  0.498  19.6  1.0
11   5.412000  0.470  23.2  1.0
12   5.224000  0.478  22.4  1.0
13   5.268000  0.398  22.6  1.0
14   4.054000  0.422  17.6  1.0
15   3.384000  0.282  14.2  1.0
16   3.270000  0.152  13.8  1.0
17   3.430000  0.156  14.4  1.0
18   3.266000  0.000  13.8  1.0
19   3.728000  0.000  16.4  1.0
20   5.894000  0.000  25.4  1.0
21   7.706000  0.000  33.2  1.0
22   7.026000  0.000  30.6  1.0
23   5.174000  0.000  22.0  1.0
24   4.474000  0.000  19.4  1.0
25   3.248000  0.000  13.6  1.0
26   3.236000  0.000  13.6  1.0
27   3.228000  0.000  13.6  1.0
28   3.258000  0.000  13.8  1.0
29   3.178000  0.000  13.4  1.0
..        ...    ...   ...  ...
970  2.424000  0.072  10.0  1.0
971  1.258000  0.184   6.8  1.0
972  0.370000  0.206   1.8  1.0
973  0.786000  0.202   4.8  1.0
974  2.474000  0.176  10.4  1.0
975  2.474000  0.176  10.4  1.0
976  2.488000  0.178  10.4  1.0
977  2.486000  0.178  10.4  1.0
978  2.444000  0.130  10.2  1.0
979  2.272000  0.048   9.6  1.0
980  0.338000  0.076   1.4  1.0
981  0.290000  0.000   1.4  1.0
982  1.466000  0.000   7.4  1.0
983  2.324000  0.050   9.6  1.0
984  2.320000  0.052   9.6  1.0
985  2.308000  0.052   9.6  1.0
986  2.314000  0.054   9.6  1.0
987  2.312000  0.052   9.6  1.0
988  2.306000  0.052   9.6  1.0
989  0.444000  0.000   3.0  1.0
990  0.268000  0.000   1.2  1.0
991  1.846000  0.046   8.4  1.0
992  2.308000  0.054   9.6  1.0
993  2.290000  0.056   9.6  1.0
994  2.288000  0.056   9.6  1.0
995  2.296000  0.054   9.6  1.0
996  2.292000  0.054   9.6  1.0
997  0.370000  0.000   2.4  1.0
998  0.472000  0.000   2.4  1.0
999  3.054000  0.060  13.4  1.0

[1000 rows x 4 columns]

In [7]:
import numpy as np
import pandas as pd
path='datas/household_power_consumption_1000.txt'
df = pd.read_csv(filepath_or_buffer=path,sep=";")#使用pandas加载csv

## 对数据集增加偏置，并去除掉不需要的列
b = pd.DataFrame([1.0]*df.shape[0],columns=["b"]) #建立一列为1的dataframe，起名为b作为偏置项
df = pd.concat(objs=[df,b],axis=1)#将偏置项合并到原始dataframe

#获取Global_active_power、Global_reactive_power、Global_intensity和偏置列b的dataframe
df = df[["Global_active_power","Global_reactive_power","Global_intensity","b"]]
df = df.replace(to_replace="?",value=np.nan).dropna()
from sklearn.preprocessing import Binarizer
bimodel = Binarizer(threshold=2)
bimodel.fit_transform(df)


array([[1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.]])

In [9]:
import numpy as np
import pandas as pd
path='datas/household_power_consumption_1000.txt'
df = pd.read_csv(filepath_or_buffer=path,sep=";")#使用pandas加载csv

## 对数据集增加偏置，并去除掉不需要的列
b = pd.DataFrame([1.0]*df.shape[0],columns=["b"]) #建立一列为1的dataframe，起名为b作为偏置项
df = pd.concat(objs=[df,b],axis=1)#将偏置项合并到原始dataframe

#获取Global_active_power、Global_reactive_power、Global_intensity和偏置列b的dataframe
df = df[["Global_active_power","Global_reactive_power","Global_intensity","b"]]
df = df.replace(to_replace="?",value=np.nan).dropna()
from sklearn.preprocessing import MinMaxScaler
mmModel = MinMaxScaler(feature_range=(0,10))
mmModel.fit_transform(df)


array([[6.872     , 8.25757576, 6.85185185, 0.        ],
       [6.89066667, 9.43181818, 6.85185185, 0.        ],
       [6.90933333, 9.50757576, 6.85185185, 0.        ],
       ...,
       [0.21866667, 0.        , 0.49382716, 0.        ],
       [0.35466667, 0.        , 0.49382716, 0.        ],
       [3.79733333, 1.13636364, 3.88888889, 0.        ]])

In [15]:
import numpy as np
a = np.array([[1.8, 0.2, 0.4, 0.4],
       [0.1, 0.3, 0.9, 0.3],
       [0.5, 0.7, 0.5, 0.1]])
# b = a ** 2
# b.sum(axis=0)
from sklearn.preprocessing import Normalizer
nmModel = Normalizer()
a = nmModel.transform(a)
b = a ** 2
b.sum(axis=1)

array([1., 1., 1.])

In [25]:
import pandas as pd
from sklearn import datasets


iris = datasets.load_iris()
data = pd.DataFrame(iris.data, columns=iris.feature_names)
data['class'] = iris.target
X = data[data.columns.drop('class')]
Y = data['class']

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=3).fit(X,Y)
print(model.score(X,Y))

from sklearn.decomposition import PCA
pcaModel = PCA(n_components=2)
pcaModel.fit(X)
X = pcaModel.transform(X)
model = DecisionTreeClassifier(max_depth=3).fit(X,Y)
print(model.score(X,Y))

0.9733333333333334
0.9466666666666667


In [28]:
import pandas as pd
from sklearn import datasets
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

iris = datasets.load_iris()
data = pd.DataFrame(iris.data, columns=iris.feature_names)
data['class'] = iris.target
X = data[data.columns.drop('class')]
Y = data['class']

lda = LinearDiscriminantAnalysis(n_components=2)
lda.fit(X, Y)
X = lda.transform(X)
model = DecisionTreeClassifier(max_depth=3).fit(X,Y)
print(model.score(X,Y))


0.9866666666666667
