In [37]:
import numpy as np
np.random.beta(2000,2000)#能产生1个出自beta(20,20)分布的样本，可以看出出现0.5的可能性最大。
np.random.beta(1000,3000)#能产生1个出自beta(10,30)分布的样本，可以看出出现0.25的可能性最大。


array([0.99397147, 0.99831305])

In [35]:
np.random.dirichlet((100,1000,1000,1000,1000,1000))

array([0.01777618, 0.19572321, 0.19415619, 0.19422402, 0.19856968,
       0.19955072])

In [38]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer
from sklearn.model_selection import train_test_split
df = pd.read_csv("datas/bayes_hangkong_tiyu.txt",header=None)
X = df[1]
Y = df[0]
print("X")
print(X.head())

tfCoder = CountVectorizer(token_pattern="[\u4e00-\u9fa5]+")
X2 = tfCoder.fit_transform(X)
dic = tfCoder.vocabulary_
print("打印TF字典")
# print(dic){'宇航': 12538, '学报': 12459, '空间': 28636,

print("训练数据转为TF")
print(X2.shape)
# len(tfCoder.vocabulary_)39515
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components =2,
                                random_state=0)
docres = lda.fit_transform(X2)

# print(dic)
print(docres)
print(docres.argmax(axis=1))
print(sum(docres.argmax(axis=1)==Y.values)/docres.shape[0])
print ("lda.components_",lda.components_.shape)
print (np.argsort(lda.components_))
a = np.argsort(lda.components_)
print("a",a)
b = [i[-50:] for i in a.tolist()]
dic = {v:k for k,v in dic.items() }
for i in b:
    for j in i:
        print(dic[j])
    print()


X
0    宇航 学报 journal of astronautics vol no 空间 辐射 散热器...
1    航空 工程 维修 aviation engineering maintenance no 飞...
2    航空 工程 维修 aviation engineering maintenance no 双...
3    航空 工程 维修 aviation engineering maintenance no 机...
4    航空 工程 维修 aviation engineering maintenance no 介...
Name: 1, dtype: object
打印TF字典
训练数据转为TF
(1320, 39515)


d:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:536: DeprecationWarning: The default value for 'learning_method' will be changed from 'online' to 'batch' in the release 0.20. This warning was introduced in 0.18.
  DeprecationWarning)


[[9.99417172e-01 5.82828207e-04]
 [9.48272130e-01 5.17278701e-02]
 [8.36948741e-01 1.63051259e-01]
 ...
 [1.73361605e-03 9.98266384e-01]
 [2.72210690e-04 9.99727789e-01]
 [3.21560981e-04 9.99678439e-01]]
[0 0 0 ... 1 1 1]
0.9719696969696969
lda.components_ (2, 39515)
[[21051 13624 33775 ... 35179 19594 29264]
 [ 6931 20505  5995 ...  7991  3288 19038]]
a [[21051 13624 33775 ... 35179 19594 29264]
 [ 6931 20505  5995 ...  7991  3288 19038]]
分布
确定
使用
得到
具有
提高
工艺
故障
信号
要求
条件
状态
问题
不同
应用
实验
通过
性能
本文
误差
材料
工作
叶片
变化
航空
时间
由于
速度
温度
过程
参数
数据
发动机
试验
影响
研究
结果
可以
结构
模型
采用
控制
技术
设计
分析
测量
计算
进行
方法
系统

水平
方面
目标
训练
过程
国家
作用
自己
方法
可以
基础
心理
需要
运动
重要
理论
要求
建设
他们
经济
我国
能力
知识
内容
中国
学科
管理
培养
科学
改革
提高
思想
进行
问题
文化
学习
研究
我们
工作
素质
课程
教师
活动
学校
社会
教学
学生
发展
体育
教育

